### Suche mit vorhandener Kunde-ID als admin
GRAPHQL {{baseUrl}}/graphql

query {
  mannschaftsmitglied(id: "00000000-0000-0000-0000-000000000001") {
    nachname
  }
}

### Suche mit nicht-vorhandener Kunde-ID als admin
GRAPHQL {{baseUrl}}/graphql

query {
  mannschaftsmitglied(id: "ffffffff-ffff-ffff-ffff-ffffffffffff") {
    nachname
  }
}

### Suche mit vorhandener Kunde-ID als admin
GRAPHQL {{baseUrl}}/graphql

query {
  mannschaftsmitglied(id: "00000000-0000-0000-0000-000000000001") {
    nachname
    email
    mannschaft
    hasNewsletter
    geburtsdatum
    homepage
    geschlecht
    familienstand
    adresse {
      plz
      ort
    }
  }
}

### Suche alle Kunden als admin
GRAPHQL {{baseUrl}}/graphql

query {
  mannschaftsmitglieder (input: {}){
    id
    nachname
    mannschaft
    hasNewsletter
    geburtsdatum
    homepage
    geschlecht
    familienstand
    adresse {
      plz
      ort
    }
  }
}

### Suche Kunde mit der Emailadresse als admin
GRAPHQL {{baseUrl}}/graphql

query {
  mannschaftsmitglieder(input: {email: "admin@acme.com"}) {
    id
    nachname
    mannschaft
    hasNewsletter
    geburtsdatum
    homepage
    geschlecht
    familienstand
    adresse {
      plz
      ort
    }
  }
}

### Suche Kunde mit nicht-vorhandener Emailadresse als admin
GRAPHQL {{baseUrl}}/graphql

query {
  mannschaftsmitglieder(input: {email: "nicht.vorhanden@acme.com"}) {
    id
  }
}

### Suche Kunden mit dem Nachnamen als admin
GRAPHQL {{baseUrl}}/graphql

query {
  mannschaftsmitglieder(input: {nachname: "Admin"}) {
    id
    nachname
    email
    mannschaft
    hasNewsletter
    geburtsdatum
    homepage
    geschlecht
    familienstand
    adresse {
      plz
      ort
    }
  }
}
### Suche Kunden mit nicht-vorhandenem Nachnamen als admin
GRAPHQL {{baseUrl}}/graphql

query {
  mannschaftsmitglieder(input: {nachname: "Nichtvorhanden"}) {
    id
  }
}
